### ISSUE TITLE
notwendige Requests 

### ISSUE THREAD

**Issue by linde9821** [neighbortrader/FoodBoardApp#4]
- [ ] Get Request für User Token #3
- [ ] Post Request um User anzulegen #7 
- [ ] Get Request für alle Offer #5 
- [ ] Post Request um einen Offer anzulegen #6
